
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mrojas.graficoscompi1.analizadores.parser;

/** CUP generated class containing symbol constants. */
public class sym {
    /* terminals */
    public static final int SIGNO_MAS = 4;
    public static final int ETIQUETAS = 26;
    public static final int EJECUTAR = 21;
    public static final int UMENOS = 17;
    public static final int NUMERO_DECIMAL = 3;
    public static final int NUMERO_ENTERO = 2;
    public static final int PORCENTAJE = 30;
    public static final int TIPO = 28;
    public static final int TIPO_GRAFICO = 20;
    public static final int DOS_PUNTOS = 16;
    public static final int VALORES = 27;
    public static final int SIGNO_DIVISION = 7;
    public static final int INICIO_DECLARACION = 19;
    public static final int COMA = 14;
    public static final int SIGNO_POR = 6;
    public static final int TOTAL = 31;
    public static final int EOF = 0;
    public static final int TITULO_GRAFICO = 22;
    public static final int PARENTESIS_I = 8;
    public static final int LLAVE_I = 12;
    public static final int EXTRA = 32;
    public static final int CANTIDAD = 29;
    public static final int SIGNO_MENOS = 5;
    public static final int PARENTESIS_D = 9;
    public static final int error = 1;
    public static final int LLAVE_D = 13;
    public static final int CORCHETE_I = 10;
    public static final int EJEY = 25;
    public static final int PUNTO_COMA = 15;
    public static final int EJEX = 24;
    public static final int CORCHETE_D = 11;
    public static final int UNIR = 23;
    public static final int STRINGP = 18;
    public static final String[] terminalNames = new String[] {
            "EOF",
            "error",
            "NUMERO_ENTERO",
            "NUMERO_DECIMAL",
            "SIGNO_MAS",
            "SIGNO_MENOS",
            "SIGNO_POR",
            "SIGNO_DIVISION",
            "PARENTESIS_I",
            "PARENTESIS_D",
            "CORCHETE_I",
            "CORCHETE_D",
            "LLAVE_I",
            "LLAVE_D",
            "COMA",
            "PUNTO_COMA",
            "DOS_PUNTOS",
            "UMENOS",
            "STRINGP",
            "INICIO_DECLARACION",
            "TIPO_GRAFICO",
            "EJECUTAR",
            "TITULO_GRAFICO",
            "UNIR",
            "EJEX",
            "EJEY",
            "ETIQUETAS",
            "VALORES",
            "TIPO",
            "CANTIDAD",
            "PORCENTAJE",
            "TOTAL",
            "EXTRA"
    };
}